name: push container to heroku

on: 
  push:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: heroku login
      run: |
          cat <<EOF > ~/.netrc 
            machine api.heroku.com 
              login ${{ secrets.HEROKU_EMAIL }}
             password ${{ secrets.HEROKU_API_KEY }}
            machine git.heroku.com
              login ${{ secrets.HEROKU_EMAIL }}
             password ${{ secrets.HEROKU_API_KEY }}
           EOF
    - name: build and push to heroku
      run: |
        heroku container:login
        docker build -t registry.heroku.com/nikita-app-test3/web .
        docker push registry.heroku.com/nikita-app-test3/web
        heroku container:release web -a nikita-app-test3
        
        
    
