name: new push

on: 
  push:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: heroku login
      run: |
          cat <<EOF > ~/.netrc 
            machine api.heroku.com 
              login ${{ secrets.HEROKU_EMAIL }}
             password ${{ secrets.HEROKU_API_KEY }}
            machine git.heroku.com
              login ${{ secrets.HEROKU_EMAIL }}
             password ${{ secrets.HEROKU_API_KEY }}
           EOF
    - name: nj
      run: |
        heroku container:login
        heroku create -a nikita-app-123
        docker build -t regestry.heroku.com/nikita-app-123/web .
        docker push regestry.heroku.com/nikita-app-123/web
        heroku container:release web -a nikita-app-123
        
        
    
