name: new push

on: 
  push:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: credentials
      run: echo -e "machine api.heroku.com \n  login ${{ secrets.HEROKU_EMAIL }} \n  password ${{ secrets.HEROKU_API_KEY }} \nmachine git.heroku.com \n  login ${{ secrets.HEROKU_EMAIL }} \n  password ${{ secrets.HEROKU_API_KEY }}" > ~/.netrc
    - name: vf
      run: cat .netrc
