name: push container to heroku

on: 
  push:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Docker build
      run: docker login --username=${{ secrets.HEROKU_EMAIL }} --password=${{ secrets.HEROKU_API_KEY }} registry.heroku.com
    - name: Publish
      run: |
        heroku container:push -a ${{ secrets.HEROKU_APP_NAME }} web 
        heroku container:release -a ${{ secrets.HEROKU_APP_NAME }} web 
