name: CI

on:
  push:
    branches: [ "master" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    runs-on: ubuntu-latest
    steps: 
    - name: print hello
      run: echo "hello world from build"
      
  new:
    runs-on: ubuntu-latest
    needs: [build]
    steps: 
    - name: print hello
      run: echo "hello world from new"
  
    
      
