name: CI
env: 
  APPLICATION_NAME: "My new job"

on:
  push:
    branches: [ "master" ]
jobs:      
  new:
    runs-on: ubuntu-latest
    steps: 
    - name: clone from my rep
      uses: actions/checkout@v3
    - name: content
      run: ls -la
    - name: python run
      run: pip install flask
    - name: run
      run: python main.py &
    - name: curl
      run: curl -s http://127.0.0.1:5000/ | if grep -q Hello; then echo "good job"; fi
      
