name: CI
env: 
  APPLICATION_NAME: "My new job"

on:
  push:
    branches: [ "master" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    runs-on: ubuntu-latest
    steps: 
    - name: print hello
      run: echo "hello world from ${{ env.APPLICATION_NAME }} "
      
  new:
    runs-on: ubuntu-latest
    needs: [build]
    steps: 
    - name: clone from my rep
      uses: actions/checkout@v3
    - name: content
      run: ls -la
    - name: check python version
      run: |
        apt install software-properties-common
        add-apt-repository ppa:deadsnakes/ppa
        apt install python3.9
        python --version
  
    
      
