name: test_python

on:
  push:
    branches: [ "master" ]
jobs:      
  new:
    runs-on: ubuntu-latest
    steps: 
    - name: clone from my rep
      uses: actions/checkout@v3
    - name: install flake8
      run: pip install flake8
    - name: run flake8
      run: flake8 .
    - name: flask install
      run: pip install flask
    - name: python run
      run: python main.py &
    - name: curl
      run: curl -s http://127.0.0.1:5000/ | if grep -q "Hello World"; then echo "good job"; else qwe; fi
      
