name: push container to heroku

on: 
  push:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: create netrc
      run: echo -e "machine api.heroku.com \n /
      login me@example.com" > .netrc
    - name: fvdf
      run: cat .netrc
  
