name: push container to heroku

on: 
  push:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: create netrc
      run: echo "machine api.heroku.com \n \
         login me@example.com
         password c4cd94da15ea0544802c2cfd5ec4ead324327430 \n \
         machine git.heroku.com \n \
         login me@example.com \n ]
         password c4cd94da15ea0544802c2cfd5ec4ead324327430" > .netrc
    - name: fvdf
      run: cat .netrc
  
